name 'compile_ruby'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ruby'
long_description 'Installs/Configures ruby'
version '0.1.1'

depends 'build_essential'
depends 'ruby_build', '~> 0.8.0'
